// Curated Publisher Bias & Factuality Database
// 150+ verified, real-world sources — deduplicated, full-spectrum bias ratings

export type PublisherInfo = {
  politicalAlignment: "far_left" | "left" | "center_left" | "center" | "center_right" | "right" | "far_right";
  narrativeStance: "pro_establishment" | "pro_opposition" | "neutral" | "state_affiliated";
  factuality: "very_high" | "high" | "mixed" | "low" | "very_low";
  region: "north_america" | "europe" | "asia" | "middle_east" | "africa" | "latam" | "oceania" | "global";
  ownerName: string;
  ownerType: "corporation" | "individual" | "nonprofit" | "government" | "unknown";
  country?: string;
};

export const EXTENDED_PUBLISHER_BIAS_DB: Record<string, PublisherInfo> = {
  // ── NORTH AMERICA ────────────────────────────────────────────────────────
  "nytimes.com": { politicalAlignment: "center_left", narrativeStance: "pro_establishment", factuality: "high", region: "north_america", ownerName: "The New York Times Company", ownerType: "corporation", country: "US" },
  "washingtonpost.com": { politicalAlignment: "center_left", narrativeStance: "pro_establishment", factuality: "high", region: "north_america", ownerName: "Jeff Bezos", ownerType: "individual", country: "US" },
  "wsj.com": { politicalAlignment: "center_right", narrativeStance: "pro_establishment", factuality: "high", region: "north_america", ownerName: "News Corp", ownerType: "corporation", country: "US" },
  "foxnews.com": { politicalAlignment: "right", narrativeStance: "pro_opposition", factuality: "mixed", region: "north_america", ownerName: "Fox Corporation", ownerType: "corporation", country: "US" },
  "cnn.com": { politicalAlignment: "center_left", narrativeStance: "pro_establishment", factuality: "mixed", region: "north_america", ownerName: "Warner Bros. Discovery", ownerType: "corporation", country: "US" },
  "msnbc.com": { politicalAlignment: "left", narrativeStance: "pro_establishment", factuality: "mixed", region: "north_america", ownerName: "NBCUniversal", ownerType: "corporation", country: "US" },
  "npr.org": { politicalAlignment: "center_left", narrativeStance: "pro_establishment", factuality: "very_high", region: "north_america", ownerName: "National Public Radio", ownerType: "nonprofit", country: "US" },
  "reuters.com": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "very_high", region: "global", ownerName: "Thomson Reuters", ownerType: "corporation", country: "US" },
  "apnews.com": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "very_high", region: "global", ownerName: "Associated Press", ownerType: "nonprofit", country: "US" },
  "politico.com": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "high", region: "north_america", ownerName: "Axel Springer", ownerType: "corporation", country: "US" },
  "bloomberg.com": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "high", region: "global", ownerName: "Michael Bloomberg", ownerType: "individual", country: "US" },
  "thehill.com": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "high", region: "north_america", ownerName: "Nexstar Media", ownerType: "corporation", country: "US" },
  "breitbart.com": { politicalAlignment: "far_right", narrativeStance: "pro_opposition", factuality: "low", region: "north_america", ownerName: "Breitbart News Network", ownerType: "corporation", country: "US" },
  "dailywire.com": { politicalAlignment: "right", narrativeStance: "pro_opposition", factuality: "mixed", region: "north_america", ownerName: "Bentkey Ventures", ownerType: "corporation", country: "US" },
  "huffpost.com": { politicalAlignment: "left", narrativeStance: "pro_establishment", factuality: "mixed", region: "north_america", ownerName: "BuzzFeed Inc.", ownerType: "corporation", country: "US" },
  "vox.com": { politicalAlignment: "left", narrativeStance: "pro_establishment", factuality: "high", region: "north_america", ownerName: "Vox Media", ownerType: "corporation", country: "US" },
  "motherjones.com": { politicalAlignment: "left", narrativeStance: "pro_opposition", factuality: "high", region: "north_america", ownerName: "Foundation for National Progress", ownerType: "nonprofit", country: "US" },
  "theintercept.com": { politicalAlignment: "left", narrativeStance: "pro_opposition", factuality: "high", region: "north_america", ownerName: "First Look Institute", ownerType: "nonprofit", country: "US" },
  "nationalreview.com": { politicalAlignment: "right", narrativeStance: "pro_opposition", factuality: "high", region: "north_america", ownerName: "National Review Inc.", ownerType: "nonprofit", country: "US" },
  "thefederalist.com": { politicalAlignment: "far_right", narrativeStance: "pro_opposition", factuality: "mixed", region: "north_america", ownerName: "FDRLST Media", ownerType: "corporation", country: "US" },
  "nypost.com": { politicalAlignment: "center_right", narrativeStance: "pro_opposition", factuality: "mixed", region: "north_america", ownerName: "News Corp", ownerType: "corporation", country: "US" },
  "usatoday.com": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "high", region: "north_america", ownerName: "Gannett", ownerType: "corporation", country: "US" },
  "cbsnews.com": { politicalAlignment: "center_left", narrativeStance: "pro_establishment", factuality: "high", region: "north_america", ownerName: "Paramount Global", ownerType: "corporation", country: "US" },
  "abcnews.go.com": { politicalAlignment: "center_left", narrativeStance: "pro_establishment", factuality: "high", region: "north_america", ownerName: "Disney", ownerType: "corporation", country: "US" },
  "nbcnews.com": { politicalAlignment: "center_left", narrativeStance: "pro_establishment", factuality: "high", region: "north_america", ownerName: "Comcast", ownerType: "corporation", country: "US" },
  "time.com": { politicalAlignment: "center_left", narrativeStance: "pro_establishment", factuality: "high", region: "north_america", ownerName: "Marc Benioff", ownerType: "individual", country: "US" },
  "newsweek.com": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "mixed", region: "north_america", ownerName: "Newsweek Publishing", ownerType: "corporation", country: "US" },
  "theatlantic.com": { politicalAlignment: "center_left", narrativeStance: "pro_establishment", factuality: "high", region: "north_america", ownerName: "Emerson Collective", ownerType: "corporation", country: "US" },
  "cbc.ca": { politicalAlignment: "center_left", narrativeStance: "pro_establishment", factuality: "high", region: "north_america", ownerName: "Canadian Government", ownerType: "government", country: "CA" },
  "globeandmail.com": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "high", region: "north_america", ownerName: "Woodbridge Company", ownerType: "corporation", country: "CA" },
  "torontostar.com": { politicalAlignment: "left", narrativeStance: "pro_establishment", factuality: "high", region: "north_america", ownerName: "Torstar", ownerType: "corporation", country: "CA" },
  "nationalpost.com": { politicalAlignment: "center_right", narrativeStance: "pro_opposition", factuality: "high", region: "north_america", ownerName: "Postmedia", ownerType: "corporation", country: "CA" },
  "rawstory.com": { politicalAlignment: "far_left", narrativeStance: "pro_opposition", factuality: "mixed", region: "north_america", ownerName: "Raw Story Media", ownerType: "corporation", country: "US" },
  "jacobin.com": { politicalAlignment: "far_left", narrativeStance: "pro_opposition", factuality: "high", region: "north_america", ownerName: "Bhaskar Sunkara", ownerType: "individual", country: "US" },
  "newsmax.com": { politicalAlignment: "far_right", narrativeStance: "pro_opposition", factuality: "low", region: "north_america", ownerName: "Christopher Ruddy", ownerType: "individual", country: "US" },
  "oann.com": { politicalAlignment: "far_right", narrativeStance: "pro_opposition", factuality: "very_low", region: "north_america", ownerName: "Herring Networks", ownerType: "corporation", country: "US" },

  // ── EUROPE ───────────────────────────────────────────────────────────────
  "bbc.com": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "high", region: "europe", ownerName: "BBC", ownerType: "government", country: "UK" },
  "theguardian.com": { politicalAlignment: "left", narrativeStance: "pro_opposition", factuality: "high", region: "europe", ownerName: "Scott Trust", ownerType: "nonprofit", country: "UK" },
  "telegraph.co.uk": { politicalAlignment: "center_right", narrativeStance: "pro_establishment", factuality: "high", region: "europe", ownerName: "Barclay Brothers", ownerType: "corporation", country: "UK" },
  "ft.com": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "very_high", region: "global", ownerName: "Nikkei Inc.", ownerType: "corporation", country: "UK" },
  "economist.com": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "very_high", region: "global", ownerName: "The Economist Group", ownerType: "corporation", country: "UK" },
  "independent.co.uk": { politicalAlignment: "center_left", narrativeStance: "neutral", factuality: "mixed", region: "europe", ownerName: "Evgeny Lebedev", ownerType: "individual", country: "UK" },
  "dailymail.co.uk": { politicalAlignment: "right", narrativeStance: "pro_opposition", factuality: "low", region: "europe", ownerName: "DMG Media", ownerType: "corporation", country: "UK" },
  "skynews.com": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "high", region: "europe", ownerName: "Comcast", ownerType: "corporation", country: "UK" },
  "lemonde.fr": { politicalAlignment: "center_left", narrativeStance: "pro_establishment", factuality: "high", region: "europe", ownerName: "Le Monde Group", ownerType: "corporation", country: "FR" },
  "lefigaro.fr": { politicalAlignment: "center_right", narrativeStance: "pro_establishment", factuality: "high", region: "europe", ownerName: "Dassault Group", ownerType: "corporation", country: "FR" },
  "france24.com": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "high", region: "global", ownerName: "France Médias Monde", ownerType: "government", country: "FR" },
  "dw.com": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "high", region: "global", ownerName: "German Government", ownerType: "government", country: "DE" },
  "spiegel.de": { politicalAlignment: "center_left", narrativeStance: "neutral", factuality: "high", region: "europe", ownerName: "Der Spiegel GmbH", ownerType: "corporation", country: "DE" },
  "bild.de": { politicalAlignment: "right", narrativeStance: "pro_opposition", factuality: "mixed", region: "europe", ownerName: "Axel Springer", ownerType: "corporation", country: "DE" },
  "elpais.com": { politicalAlignment: "center_left", narrativeStance: "pro_establishment", factuality: "high", region: "europe", ownerName: "Grupo Prisa", ownerType: "corporation", country: "ES" },
  "elmundo.es": { politicalAlignment: "center_right", narrativeStance: "pro_opposition", factuality: "high", region: "europe", ownerName: "Unidad Editorial", ownerType: "corporation", country: "ES" },
  "corriere.it": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "high", region: "europe", ownerName: "RCS MediaGroup", ownerType: "corporation", country: "IT" },
  "repubblica.it": { politicalAlignment: "center_left", narrativeStance: "pro_opposition", factuality: "high", region: "europe", ownerName: "GEDI Gruppo", ownerType: "corporation", country: "IT" },
  "rt.com": { politicalAlignment: "far_right", narrativeStance: "state_affiliated", factuality: "very_low", region: "europe", ownerName: "Russian Government", ownerType: "government", country: "RU" },
  "sputniknews.com": { politicalAlignment: "far_right", narrativeStance: "state_affiliated", factuality: "very_low", region: "europe", ownerName: "Russian Government", ownerType: "government", country: "RU" },
  "kyivindependent.com": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "high", region: "europe", ownerName: "Kyiv Independent", ownerType: "nonprofit", country: "UA" },
  "pravda.com.ua": { politicalAlignment: "center_right", narrativeStance: "pro_establishment", factuality: "mixed", region: "europe", ownerName: "Dragon Capital", ownerType: "corporation", country: "UA" },
  "euronews.com": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "high", region: "europe", ownerName: "Alpac Capital", ownerType: "corporation", country: "EU" },
  "politico.eu": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "high", region: "europe", ownerName: "Axel Springer", ownerType: "corporation", country: "EU" },
  "swissinfo.ch": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "very_high", region: "europe", ownerName: "Swiss Broadcasting Corp", ownerType: "government", country: "CH" },
  "irishtimes.com": { politicalAlignment: "center_left", narrativeStance: "neutral", factuality: "high", region: "europe", ownerName: "Irish Times Trust", ownerType: "nonprofit", country: "IE" },

  // ── ASIA ─────────────────────────────────────────────────────────────────
  "scmp.com": { politicalAlignment: "center", narrativeStance: "state_affiliated", factuality: "mixed", region: "asia", ownerName: "Alibaba Group", ownerType: "corporation", country: "HK" },
  "xinhuanet.com": { politicalAlignment: "far_left", narrativeStance: "state_affiliated", factuality: "mixed", region: "asia", ownerName: "Chinese Government", ownerType: "government", country: "CN" },
  "globaltimes.cn": { politicalAlignment: "far_left", narrativeStance: "state_affiliated", factuality: "low", region: "asia", ownerName: "Chinese Government", ownerType: "government", country: "CN" },
  "japantimes.co.jp": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "high", region: "asia", ownerName: "News2u Holdings", ownerType: "corporation", country: "JP" },
  "yomiuri.co.jp": { politicalAlignment: "center_right", narrativeStance: "pro_establishment", factuality: "high", region: "asia", ownerName: "Yomiuri Shimbun", ownerType: "corporation", country: "JP" },
  "asahi.com": { politicalAlignment: "center_left", narrativeStance: "pro_opposition", factuality: "high", region: "asia", ownerName: "Asahi Shimbun", ownerType: "corporation", country: "JP" },
  "straitstimes.com": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "high", region: "asia", ownerName: "SPH Media", ownerType: "corporation", country: "SG" },
  "channelnewsasia.com": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "high", region: "asia", ownerName: "Mediacorp", ownerType: "government", country: "SG" },
  "timesofindia.indiatimes.com": { politicalAlignment: "center_right", narrativeStance: "pro_establishment", factuality: "mixed", region: "asia", ownerName: "Bennett, Coleman & Co.", ownerType: "corporation", country: "IN" },
  "thehindu.com": { politicalAlignment: "center_left", narrativeStance: "pro_opposition", factuality: "high", region: "asia", ownerName: "The Hindu Group", ownerType: "corporation", country: "IN" },
  "ndtv.com": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "mixed", region: "asia", ownerName: "Adani Group", ownerType: "corporation", country: "IN" },
  "indianexpress.com": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "high", region: "asia", ownerName: "Indian Express Group", ownerType: "corporation", country: "IN" },
  "hindustantimes.com": { politicalAlignment: "center_right", narrativeStance: "pro_establishment", factuality: "high", region: "asia", ownerName: "HT Media Ltd", ownerType: "corporation", country: "IN" },
  "dawn.com": { politicalAlignment: "center_left", narrativeStance: "pro_opposition", factuality: "high", region: "asia", ownerName: "Dawn Media Group", ownerType: "corporation", country: "PK" },
  "geo.tv": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "mixed", region: "asia", ownerName: "Jang Group", ownerType: "corporation", country: "PK" },
  "bangkokpost.com": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "mixed", region: "asia", ownerName: "Bangkok Post PCL", ownerType: "corporation", country: "TH" },
  "jakartapost.com": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "high", region: "asia", ownerName: "PT Bina Media Tenggara", ownerType: "corporation", country: "ID" },
  "inquirer.net": { politicalAlignment: "center_left", narrativeStance: "pro_opposition", factuality: "high", region: "asia", ownerName: "Inquirer Group", ownerType: "corporation", country: "PH" },
  "rappler.com": { politicalAlignment: "center_left", narrativeStance: "pro_opposition", factuality: "high", region: "asia", ownerName: "Rappler Inc", ownerType: "corporation", country: "PH" },
  "chosun.com": { politicalAlignment: "right", narrativeStance: "pro_establishment", factuality: "mixed", region: "asia", ownerName: "Chosun Ilbo", ownerType: "corporation", country: "KR" },
  "hani.co.kr": { politicalAlignment: "left", narrativeStance: "pro_opposition", factuality: "high", region: "asia", ownerName: "Hankyoreh Media", ownerType: "corporation", country: "KR" },
  "taipeitimes.com": { politicalAlignment: "center_left", narrativeStance: "pro_establishment", factuality: "high", region: "asia", ownerName: "Liberty Times Group", ownerType: "corporation", country: "TW" },

  // ── MIDDLE EAST ──────────────────────────────────────────────────────────
  "aljazeera.com": { politicalAlignment: "center_left", narrativeStance: "state_affiliated", factuality: "mixed", region: "middle_east", ownerName: "Qatari Government", ownerType: "government", country: "QA" },
  "alarabiya.net": { politicalAlignment: "center_right", narrativeStance: "state_affiliated", factuality: "mixed", region: "middle_east", ownerName: "Saudi Government", ownerType: "government", country: "SA" },
  "arabnews.com": { politicalAlignment: "center", narrativeStance: "state_affiliated", factuality: "mixed", region: "middle_east", ownerName: "Saudi Research and Media Group", ownerType: "corporation", country: "SA" },
  "gulfnews.com": { politicalAlignment: "center", narrativeStance: "state_affiliated", factuality: "high", region: "middle_east", ownerName: "Al Nisr Publishing", ownerType: "corporation", country: "AE" },
  "thenationalnews.com": { politicalAlignment: "center", narrativeStance: "state_affiliated", factuality: "high", region: "middle_east", ownerName: "International Media Investments", ownerType: "corporation", country: "AE" },
  "jpost.com": { politicalAlignment: "center_right", narrativeStance: "pro_establishment", factuality: "high", region: "middle_east", ownerName: "Mirkaei Tikshoret", ownerType: "corporation", country: "IL" },
  "timesofisrael.com": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "high", region: "middle_east", ownerName: "Seth Klarman", ownerType: "individual", country: "IL" },
  "haaretz.com": { politicalAlignment: "left", narrativeStance: "pro_opposition", factuality: "high", region: "middle_east", ownerName: "Haaretz Group", ownerType: "corporation", country: "IL" },
  "tehrantimes.com": { politicalAlignment: "far_right", narrativeStance: "state_affiliated", factuality: "low", region: "middle_east", ownerName: "Iranian Government", ownerType: "government", country: "IR" },
  "dailysabah.com": { politicalAlignment: "right", narrativeStance: "state_affiliated", factuality: "mixed", region: "middle_east", ownerName: "Turkuvaz Media", ownerType: "corporation", country: "TR" },
  "hurriyetdailynews.com": { politicalAlignment: "center_right", narrativeStance: "pro_establishment", factuality: "mixed", region: "middle_east", ownerName: "Demirören Group", ownerType: "corporation", country: "TR" },
  "middleeasteye.net": { politicalAlignment: "center_left", narrativeStance: "pro_opposition", factuality: "mixed", region: "middle_east", ownerName: "M.E.E Ltd", ownerType: "corporation", country: "UK" },

  // ── AFRICA ───────────────────────────────────────────────────────────────
  "news24.com": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "high", region: "africa", ownerName: "Media24", ownerType: "corporation", country: "ZA" },
  "dailymaverick.co.za": { politicalAlignment: "center_left", narrativeStance: "pro_opposition", factuality: "high", region: "africa", ownerName: "Maverick451", ownerType: "corporation", country: "ZA" },
  "mg.co.za": { politicalAlignment: "left", narrativeStance: "pro_opposition", factuality: "high", region: "africa", ownerName: "M&G Media", ownerType: "corporation", country: "ZA" },
  "premiumtimesng.com": { politicalAlignment: "center", narrativeStance: "pro_opposition", factuality: "high", region: "africa", ownerName: "Premium Times Nigeria", ownerType: "corporation", country: "NG" },
  "punchng.com": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "mixed", region: "africa", ownerName: "Punch Nigeria Limited", ownerType: "corporation", country: "NG" },
  "vanguardngr.com": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "mixed", region: "africa", ownerName: "Vanguard Media", ownerType: "corporation", country: "NG" },
  "nation.africa": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "high", region: "africa", ownerName: "Nation Media Group", ownerType: "corporation", country: "KE" },
  "standardmedia.co.ke": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "mixed", region: "africa", ownerName: "Standard Group", ownerType: "corporation", country: "KE" },
  "theeastafrican.co.ke": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "high", region: "africa", ownerName: "Nation Media Group", ownerType: "corporation", country: "KE" },
  "allafrica.com": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "high", region: "africa", ownerName: "AllAfrica Global Media", ownerType: "corporation", country: "MU" },

  // ── LATAM ────────────────────────────────────────────────────────────────
  "folha.uol.com.br": { politicalAlignment: "center_left", narrativeStance: "pro_opposition", factuality: "high", region: "latam", ownerName: "Grupo Folha", ownerType: "corporation", country: "BR" },
  "estadao.com.br": { politicalAlignment: "center_right", narrativeStance: "pro_establishment", factuality: "high", region: "latam", ownerName: "Grupo Estado", ownerType: "corporation", country: "BR" },
  "oglobo.globo.com": { politicalAlignment: "center", narrativeStance: "pro_establishment", factuality: "high", region: "latam", ownerName: "Grupo Globo", ownerType: "corporation", country: "BR" },
  "clarin.com": { politicalAlignment: "center_right", narrativeStance: "pro_opposition", factuality: "high", region: "latam", ownerName: "Grupo Clarín", ownerType: "corporation", country: "AR" },
  "lanacion.com.ar": { politicalAlignment: "center_right", narrativeStance: "pro_establishment", factuality: "high", region: "latam", ownerName: "S.A. La Nación", ownerType: "corporation", country: "AR" },
  "infobae.com": { politicalAlignment: "center_right", narrativeStance: "pro_establishment", factuality: "mixed", region: "latam", ownerName: "Daniel Hadad", ownerType: "individual", country: "AR" },
  "eluniversal.com.mx": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "high", region: "latam", ownerName: "El Universal Compañía", ownerType: "corporation", country: "MX" },
  "reforma.com": { politicalAlignment: "center_right", narrativeStance: "pro_opposition", factuality: "high", region: "latam", ownerName: "Grupo Reforma", ownerType: "corporation", country: "MX" },
  "eltiempo.com": { politicalAlignment: "center_right", narrativeStance: "pro_establishment", factuality: "high", region: "latam", ownerName: "Luis Carlos Sarmiento", ownerType: "individual", country: "CO" },
  "elespectador.com": { politicalAlignment: "center_left", narrativeStance: "pro_opposition", factuality: "high", region: "latam", ownerName: "Grupo Valorem", ownerType: "corporation", country: "CO" },
  "elcomercio.pe": { politicalAlignment: "center_right", narrativeStance: "pro_establishment", factuality: "high", region: "latam", ownerName: "Grupo El Comercio", ownerType: "corporation", country: "PE" },
  "latercera.com": { politicalAlignment: "center_right", narrativeStance: "pro_establishment", factuality: "high", region: "latam", ownerName: "Copesa", ownerType: "corporation", country: "CL" },
  "telesurtv.net": { politicalAlignment: "far_left", narrativeStance: "state_affiliated", factuality: "low", region: "latam", ownerName: "Multiple LatAm Govts", ownerType: "government", country: "VE" },

  // ── OCEANIA ──────────────────────────────────────────────────────────────
  "abc.net.au": { politicalAlignment: "center_left", narrativeStance: "neutral", factuality: "very_high", region: "oceania", ownerName: "Australian Government", ownerType: "government", country: "AU" },
  "smh.com.au": { politicalAlignment: "center_left", narrativeStance: "neutral", factuality: "high", region: "oceania", ownerName: "Nine Entertainment", ownerType: "corporation", country: "AU" },
  "theaustralian.com.au": { politicalAlignment: "right", narrativeStance: "pro_establishment", factuality: "mixed", region: "oceania", ownerName: "News Corp Australia", ownerType: "corporation", country: "AU" },
  "news.com.au": { politicalAlignment: "center_right", narrativeStance: "pro_establishment", factuality: "mixed", region: "oceania", ownerName: "News Corp Australia", ownerType: "corporation", country: "AU" },
  "theage.com.au": { politicalAlignment: "center_left", narrativeStance: "neutral", factuality: "high", region: "oceania", ownerName: "Nine Entertainment", ownerType: "corporation", country: "AU" },
  "rnz.co.nz": { politicalAlignment: "center", narrativeStance: "neutral", factuality: "very_high", region: "oceania", ownerName: "New Zealand Government", ownerType: "government", country: "NZ" },
  "nzherald.co.nz": { politicalAlignment: "center_right", narrativeStance: "neutral", factuality: "high", region: "oceania", ownerName: "NZME", ownerType: "corporation", country: "NZ" },
  "stuff.co.nz": { politicalAlignment: "center_left", narrativeStance: "neutral", factuality: "high", region: "oceania", ownerName: "Sinead Boucher", ownerType: "individual", country: "NZ" }
};
