// Massive expansion of RSS feeds for global coverage
export type RSSSource = {
  url: string;
  publisherName: string;
  category: string;
  region: "India" | "USA" | "UK" | "Global";
};

export const RSS_SOURCES: RSSSource[] = [
  // --- GLOBAL ---
  { url: "https://www.reutersagency.com/feed/", publisherName: "Reuters", category: "General", region: "Global" },
  { url: "https://apnews.com/help/rss", publisherName: "Associated Press", category: "General", region: "Global" },
  { url: "https://www.aljazeera.com/xml/rss/all.xml", publisherName: "Al Jazeera", category: "General", region: "Global" },
  { url: "https://feeds.bbci.co.uk/news/world/rss.xml", publisherName: "BBC World", category: "General", region: "Global" },
  { url: "https://www.france24.com/en/rss", publisherName: "France 24", category: "General", region: "Global" },
  { url: "https://rss.dw.com/xml/rss-en-all", publisherName: "Deutsche Welle", category: "General", region: "Global" },
  { url: "https://www.economist.com/sections/international/rss.xml", publisherName: "The Economist", category: "General", region: "Global" },
  { url: "https://www.ft.com/?format=rss", publisherName: "Financial Times", category: "Business", region: "Global" },
  { url: "https://scmp.com/rss/91/feed", publisherName: "SCMP", category: "General", region: "Global" },

  // --- USA ---
  { url: "http://rss.cnn.com/rss/cnn_topstories.rss", publisherName: "CNN", category: "General", region: "USA" },
  { url: "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/section/world/rss.xml", publisherName: "New York Times", category: "General", region: "USA" },
  { url: "https://feeds.washingtonpost.com/rss/world", publisherName: "Washington Post", category: "General", region: "USA" },
  { url: "https://www.foxnews.com/about/rss/", publisherName: "Fox News", category: "General", region: "USA" },
  { url: "https://www.wsj.com/xml/rss/3_7085.xml", publisherName: "WSJ", category: "Business", region: "USA" },
  { url: "https://www.politico.com/rss/politicopicks.xml", publisherName: "Politico", category: "Politics", region: "USA" },
  { url: "https://www.theatlantic.com/feed/all/", publisherName: "The Atlantic", category: "General", region: "USA" },
  { url: "https://www.npr.org/rss/rss.php?id=1001", publisherName: "NPR", category: "General", region: "USA" },
  { url: "https://abcnews.go.com/abcnews/topstories", publisherName: "ABC News", category: "General", region: "USA" },
  { url: "https://www.cbsnews.com/latest/rss/main", publisherName: "CBS News", category: "General", region: "USA" },
  { url: "https://thehill.com/homenews/feed/", publisherName: "The Hill", category: "Politics", region: "USA" },
  { url: "https://www.axios.com/feeds/feed.rss", publisherName: "Axios", category: "General", region: "USA" },
  { url: "https://www.dailywire.com/rss.xml", publisherName: "Daily Wire", category: "General", region: "USA" },
  { url: "https://www.breitbart.com/feed/", publisherName: "Breitbart", category: "General", region: "USA" },
  { url: "https://nypost.com/feed/", publisherName: "NY Post", category: "General", region: "USA" },
  { url: "https://www.nationalreview.com/feed/", publisherName: "National Review", category: "General", region: "USA" },

  // --- INDIA ---
  { url: "https://www.thehindu.com/news/national/feeder/default.rss", publisherName: "The Hindu", category: "General", region: "India" },
  { url: "https://indianexpress.com/feed/", publisherName: "Indian Express", category: "General", region: "India" },
  { url: "https://www.ndtv.com/rss/top-stories", publisherName: "NDTV", category: "General", region: "India" },
  { url: "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", publisherName: "Times of India", category: "General", region: "India" },
  { url: "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml", publisherName: "Hindustan Times", category: "General", region: "India" },
  { url: "https://www.news18.com/commonfeeds/v1/eng/rss/india.xml", publisherName: "News18", category: "General", region: "India" },
  { url: "https://economictimes.indiatimes.com/rssfeedstopstories.cms", publisherName: "Economic Times", category: "Business", region: "India" },
  { url: "https://www.business-standard.com/rss/latest-news-1.rss", publisherName: "Business Standard", category: "Business", region: "India" },
  { url: "https://zeenews.india.com/rss/india-national-news.xml", publisherName: "Zee News", category: "General", region: "India" },
  { url: "https://scroll.in/feed", publisherName: "Scroll", category: "General", region: "India" },
  { url: "https://www.thequint.com/rss/hot-news.xml", publisherName: "The Quint", category: "General", region: "India" },
  { url: "https://thewire.in/rss", publisherName: "The Wire", category: "General", region: "India" },
  { url: "https://www.opindia.com/feed/", publisherName: "OpIndia", category: "General", region: "India" },
  { url: "https://swarajyamag.com/feed", publisherName: "Swarajya", category: "General", region: "India" },
  { url: "https://theprint.in/feed/", publisherName: "The Print", category: "General", region: "India" },

  // --- UK ---
  { url: "https://feeds.bbci.co.uk/news/rss.xml", publisherName: "BBC News UK", category: "General", region: "UK" },
  { url: "https://www.theguardian.com/uk/rss", publisherName: "The Guardian UK", category: "General", region: "UK" },
  { url: "https://www.independent.co.uk/news/uk/rss", publisherName: "The Independent", category: "General", region: "UK" },
  { url: "https://www.telegraph.co.uk/rss.xml", publisherName: "The Telegraph", category: "General", region: "UK" },
  { url: "https://news.sky.com/feeds/rss/uk.xml", publisherName: "Sky News UK", category: "General", region: "UK" },

  // --- TECHNOLOGY & SCIENCE (Global) ---
  { url: "https://techcrunch.com/feed/", publisherName: "TechCrunch", category: "Technology", region: "Global" },
  { url: "https://www.theverge.com/rss/index.xml", publisherName: "The Verge", category: "Technology", region: "Global" },
  { url: "https://www.wired.com/feed/rss", publisherName: "Wired", category: "Technology", region: "Global" },
  { url: "https://arstechnica.com/feed/", publisherName: "Ars Technica", category: "Technology", region: "Global" },
  { url: "https://www.cnet.com/rss/news/", publisherName: "CNET", category: "Technology", region: "Global" },
  { url: "https://gizmodo.com/rss", publisherName: "Gizmodo", category: "Technology", region: "Global" },
  { url: "https://www.nature.com/nature.rss", publisherName: "Nature", category: "Science", region: "Global" },
  { url: "https://www.scientificamerican.com/section/reuters/rss/", publisherName: "Scientific American", category: "Science", region: "Global" },

  // --- ENTERPRISE SCALE ADDITIONS (Global Broad) ---
  { url: "https://www.smh.com.au/rss/feed.xml", publisherName: "Sydney Morning Herald", category: "General", region: "Global" },
  { url: "https://www.theage.com.au/rss/feed.xml", publisherName: "The Age", category: "General", region: "Global" },
  { url: "https://www.cbc.ca/cctoc/rss/topstories", publisherName: "CBC", category: "General", region: "Global" },
  { url: "https://www.thestar.com/feeds/articles.topstories.rss", publisherName: "The Star", category: "General", region: "Global" },
  { url: "https://www.globeandmail.com/arc/outboundfeeds/rss/category/world/", publisherName: "Globe and Mail", category: "General", region: "Global" },
  { url: "https://nationalpost.com/feed/", publisherName: "National Post", category: "General", region: "Global" },
  { url: "https://www.haaretz.com/cmlink/1.4623101", publisherName: "Haaretz", category: "General", region: "Global" },
  { url: "https://www.jpost.com/rss/rssfeeds.aspx?tid=1", publisherName: "Jerusalem Post", category: "General", region: "Global" },
  { url: "https://www.timesofisrael.com/feed/", publisherName: "Times of Israel", category: "General", region: "Global" },
  { url: "https://www.straitstimes.com/news/world/rss.xml", publisherName: "Straits Times", category: "General", region: "Global" },
  { url: "https://www.bangkokpost.com/rss/data/topstories.xml", publisherName: "Bangkok Post", category: "General", region: "Global" },
  { url: "https://www.thejakartapost.com/rss/news", publisherName: "Jakarta Post", category: "General", region: "Global" },
  { url: "https://www.philstar.com/rss/headlines", publisherName: "PhilStar", category: "General", region: "Global" },
  { url: "https://www.manilatimes.net/feed", publisherName: "Manila Times", category: "General", region: "Global" },
  { url: "https://lowyinstitute.org/the-interpreter/rss.xml", publisherName: "The Interpreter", category: "General", region: "Global" },
  { url: "https://www.foreignaffairs.com/rss.xml", publisherName: "Foreign Affairs", category: "Politics", region: "Global" },
  { url: "https://www.japantimes.co.jp/feed/", publisherName: "Japan Times", category: "General", region: "Global" },

  // --- ADDITIONAL GLOBAL & REGIONAL ---
  { url: "https://www.latimes.com/world/rss2.0.xml", publisherName: "LA Times World", category: "General", region: "USA" },
  { url: "https://www.chicagotribune.com/arc/outboundfeeds/rss/category/news/?outputType=xml", publisherName: "Chicago Tribune", category: "General", region: "USA" },
  { url: "https://www.bostonglobe.com/rss/world", publisherName: "Boston Globe", category: "General", region: "USA" },
  { url: "https://theintercept.com/feed/?rss", publisherName: "The Intercept", category: "General", region: "USA" },
  { url: "https://www.motherjones.com/feed/", publisherName: "Mother Jones", category: "General", region: "USA" },
  { url: "https://www.newyorker.com/feed/news", publisherName: "The New Yorker", category: "General", region: "USA" },
  { url: "https://www.economist.com/the-world-this-week/rss.xml", publisherName: "Economist Week", category: "General", region: "Global" },
  { url: "https://www.thequint.com/rss/politics.xml", publisherName: "The Quint Politics", category: "Politics", region: "India" },
  { url: "https://thewire.in/rss/politics", publisherName: "The Wire Politics", category: "Politics", region: "India" },
  { url: "https://scroll.in/feed/politics", publisherName: "Scroll Politics", category: "Politics", region: "India" },
  { url: "https://www.livemint.com/rss/politics", publisherName: "Livemint Politics", category: "Politics", region: "India" },
  { url: "https://www.deccanherald.com/rss/national.rss", publisherName: "Deccan Herald", category: "General", region: "India" },
  { url: "https://www.dnaindia.com/feeds/india.xml", publisherName: "DNA India", category: "General", region: "India" },
  { url: "https://www.tribuneindia.com/rss/feed", publisherName: "The Tribune", category: "General", region: "India" },
  { url: "https://www.greaterkashmir.com/feed", publisherName: "Greater Kashmir", category: "General", region: "India" },
  { url: "https://www.firstpost.com/rss/india.xml", publisherName: "Firstpost", category: "General", region: "India" },
  { url: "https://www.thehindu.com/opinion/feeder/default.rss", publisherName: "The Hindu Opinion", category: "General", region: "India" },
  { url: "https://www.aljazeera.com/xml/rss/all.xml", publisherName: "Al Jazeera EN", category: "General", region: "Global" },
  { url: "https://rss.dw.com/xml/rss-en-world", publisherName: "DW World", category: "General", region: "Global" },
  { url: "https://www.france24.com/en/france/rss", publisherName: "France24 News", category: "General", region: "Global" },
  { url: "https://news.google.com/rss/search?q=when:24h&hl=en-IN&gl=IN&ceid=IN:en", publisherName: "Google News India", category: "General", region: "India" },
  { url: "https://news.google.com/rss/search?q=when:24h&hl=en-US&gl=US&ceid=US:en", publisherName: "Google News USA", category: "General", region: "USA" },
  { url: "https://www.washingtontimes.com/rss/headlines/news/world/", publisherName: "Washington Times", category: "General", region: "USA" },
  { url: "https://www.breitbart.com/politics/feed/", publisherName: "Breitbart Politics", category: "Politics", region: "USA" },
  { url: "https://www.huffpost.com/section/front-page/feed", publisherName: "HuffPost", category: "General", region: "USA" },
  { url: "https://www.salon.com/feed", publisherName: "Salon", category: "General", region: "USA" },
  { url: "https://fee.org/rss", publisherName: "FEE", category: "Politics", region: "USA" },
  { url: "https://www.reason.com/feed/", publisherName: "Reason", category: "Politics", region: "USA" },
  { url: "https://www.vox.com/rss/index.xml", publisherName: "Vox", category: "General", region: "USA" },
  { url: "https://www.slate.com/all.full.rss", publisherName: "Slate", category: "General", region: "USA" },
  { url: "https://www.propublica.org/feeds/propublica/main", publisherName: "ProPublica", category: "General", region: "USA" },
  { url: "https://www.rt.com/rss/news/", publisherName: "RT News", category: "General", region: "Global" },
  { url: "https://www.presstv.ir/rss", publisherName: "Press TV", category: "General", region: "Global" },
  { url: "https://www.sciencedaily.com/rss/all.xml", publisherName: "ScienceDaily", category: "Science", region: "Global" },
  { url: "https://feeds.feedburner.com/spacenewsfeed", publisherName: "SpaceNews", category: "Science", region: "Global" },
  { url: "https://www.medscape.com/cx/rssfeed/all.xml", publisherName: "Medscape", category: "Science", region: "Global" },
  { url: "https://www.investopedia.com/rss/news", publisherName: "Investopedia", category: "Business", region: "Global" },
  { url: "https://www.marketwatch.com/rss/topstories", publisherName: "MarketWatch", category: "Business", region: "Global" },
  { url: "https://www.cnbc.com/id/100003114/device/rss/rss.html", publisherName: "CNBC", category: "Business", region: "Global" },
  { url: "https://www.reuters.com/rssFeed/businessNews", publisherName: "Reuters Business", category: "Business", region: "Global" },
  { url: "https://www.bloomberg.com/politics/feeds/site.xml", publisherName: "Bloomberg Politics", category: "Politics", region: "Global" },
];
